"""Pydantic schemas for Agentic RAG endpoints."""

from pydantic import BaseModel, Field

from .ask import SourceChunk


class ReasoningStep(BaseModel):
    """Schema representing an intermediate reasoning or decision step in agentic RAG workflow."""

    node: str = Field(..., description="Name of the node in the agent graph")
    decision: str = Field(..., description="Decision or outcome produced by node execution")
    detail: str = Field(..., description="Detailed explanation or log of the decision")


class AgenticAskResponse(BaseModel):
    """Response payload for Agentic RAG question-answering."""

    answer: str = Field(..., description="Grounded answer generated by LLM agent workflow")
    sources: list[SourceChunk] = Field(
        default_factory=list, description="List of source paper chunks used for attribution"
    )
    reasoning_steps: list[ReasoningStep] = Field(
        default_factory=list,
        description="Sequence of reasoning steps taken during agent execution",
    )
    original_query: str = Field("", description="Original user query")
    final_query: str = Field("", description="Final query used for generation after rewrites")
    retrieved_chunk_count: int = Field(0, description="Total candidate chunks retrieved")
    used_chunk_count: int = Field(0, description="Chunks used in generation")
    rewrite_count: int = Field(0, description="Number of query rewrites performed")
    rejected: bool = Field(False, description="True if query was rejected by guardrails or grading")
    took_ms: float = Field(0.0, description="Total end-to-end processing time in milliseconds")
    prompt_tokens: int = Field(0, description="Prompt tokens used by LLM call(s)")
    completion_tokens: int = Field(0, description="Completion tokens generated by LLM call(s)")
    cached: bool = Field(False, description="True if response was served from Redis cache")
