"""Pydantic schemas for RAG Ask endpoints."""

from datetime import date
from typing import Literal

from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    """Request payload for RAG question-answering."""

    query: str = Field(..., min_length=1, description="Question to answer using arXiv papers")
    mode: Literal["keyword", "semantic", "hybrid"] = Field(
        "hybrid",
        description="Retrieval mode used to fetch grounding context chunks",
    )
    category: str | None = Field(None, description="Filter by arXiv category (e.g. 'cs.AI')")
    date_from: date | None = Field(None, description="Filter papers published on or after date")
    date_to: date | None = Field(None, description="Filter papers published on or before date")
    top_k: int = Field(8, ge=1, le=20, description="Number of candidate chunks to retrieve")


class SourceChunk(BaseModel):
    """Attribution item representing a source paper chunk used in RAG response."""

    paper_id: str
    title: str
    section_name: str
    snippet: str = Field(..., description="First 300 characters of chunk text for citation preview")
    relevance_score: float
    pdf_url: str


class AskResponse(BaseModel):
    """Response payload for RAG question-answering."""

    answer: str = Field(..., description="Grounded answer generated by LLM")
    sources: list[SourceChunk] = Field(..., description="List of source paper chunks used for attribution")
    retrieved_chunk_count: int = Field(..., description="Total candidate chunks retrieved by search")
    used_chunk_count: int = Field(..., description="Chunks that fit within LLM context token budget")
    took_ms: float = Field(..., description="Total end-to-end processing time in milliseconds")
    prompt_tokens: int = Field(..., description="Prompt tokens used by LLM call")
    completion_tokens: int = Field(..., description="Completion tokens generated by LLM call")
    cached: bool = Field(False, description="True if response was served from Redis cache")
